spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/planner
    username: postgres
    password: postgres
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#  liquibase:
#    url: jdbc:postgresql://localhost:5432/postgres
#    user: postgres
#    password: postgres
#    change-log: classpath:/liquibase/changelog.yml
#    default-schema: app_planner

  liquibase:
    url: jdbc:postgresql://localhost:5432/planner
    changeLog: classpath:/db/changelog.yaml
    enabled: true
